spring:
  application.name: simple-task-tracker-authorization-server

  # Database props
  datasource:
    url: jdbc:postgresql://postgres:5432/task_tracker
    username: postgres
    password: postgres
  jpa:
    show-sql: true

server.port: 8080