spring:
  application.name: user-client-service

  # Database props
  datasource:
    url: jdbc:postgresql://postgres:5432/task_tracker
    username: postgres
    password: postgres
  jpa:
    show-sql: true

server.port: 8080

jwksUri: http://authorization:8080/oauth2/jwks