CREATE TABLE "clients" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" varchar(50) UNIQUE NOT NULL,
  "secret" varchar(72) NOT NULL,
  "scope" varchar(50) NOT NULL,
  "auth_method" varchar(50) NOT NULL,
  "grant_type" varchar(50) NOT NULL,
  "redirect_uri" varchar(256) NOT NULL
);

INSERT INTO clients ("client_id", "secret", "scope", "auth_method", "grant_type", "redirect_uri")
VALUES ('client', '$2a$10$Npm0AEhLPLSc1N1LW/aFTew/APjjYFTQWZvmNTPW4irnZFlRzgkK6', 'openid', 'client_secret_basic', 'authorization_code', 'https://springone.io/authorized');