-- roles
--CREATE TYPE roles
--AS
--ENUM('ROOT','ADMIN','USER');

-- users
CREATE TABLE "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "password" varchar(72) NOT NULL,
  "role" varchar(10) NOT NULL
);

INSERT INTO "users" ("username", "email", "password", "role")
VALUES ('bill', 'bill@mail.com', '$2a$10$GrAs7DFUTbO2cXTBn96S7Oj4pLA5T8u2fZ5D1GlizbxQfEeN2CbHG', 'ROOT');

-- clients
CREATE TABLE "clients" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" varchar(50) UNIQUE NOT NULL,
  "secret" varchar(72) NOT NULL,
  "scope" varchar(50) NOT NULL,
  "auth_method" varchar(50) NOT NULL,
  "grant_type" varchar(50) NOT NULL,
  "redirect_uri" varchar(256) NOT NULL
);

INSERT INTO clients ("client_id", "secret", "scope", "auth_method", "grant_type", "redirect_uri")
VALUES ('client', '$2a$10$Npm0AEhLPLSc1N1LW/aFTew/APjjYFTQWZvmNTPW4irnZFlRzgkK6', 'openid', 'client_secret_basic', 'authorization_code', 'https://springone.io/authorized');