CREATE TABLE "clients" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" varchar(50) UNIQUE NOT NULL,
  "secret" varchar(72) NOT NULL,
  "scope" varchar(50) NOT NULL,
  "auth_method" varchar(50) NOT NULL,
  "grant_type" varchar(50) NOT NULL,
  "redirect_uri" varchar(256) NOT NULL
);

INSERT INTO clients ()